[DEVICE]
LastDateTime=21.05.2022 17:26:04
Location=БКО
Description=
ID=xxxxx775 DExS.SMFCB v1.10.5.0 21.05.2022 www.intmash.ru
MCU=1

[RAM]
p00020=DExS_PWR_OK/Качество сети выпрямителя и исправность DExS.PWR/TBit/x0000/1/r0000.0/0/1/0/
p00021=DExS_PWR_LNK/Наличие связи с платой DExS.PWR/TBit/x0000/2/r0000.1/0/1/0/
p00022=SyncRect/Наличие синхроимпульсов выпрямителя/TBit/x0000/4/r0000.2/0/1/0/
p00023=PWR/Выпрямитель включен/TBit/x0000/8/r0000.3/0/1/0/
p00024=Chop/Инвертирование/TBit/x0000/16/r0000.4/0/1/0/

[CD]
p60000=SN/серийный номер/TDWORD/xE000/rC000/*/1/4/x00000303/
p60200=tdir_Modbus_RS485/пауза перед ответом/TWORD/xE004/rC002/us/1/2//1/x0014/
p60300=tdir_Modbus_option/пауза перед ответом/TWORD/xE006/rC003/us/1/2//1/x0014/
p60400=tdir_Modbus_USB/пауза перед ответом/TWORD/xE008/rC004/us/1/2//1/x0014/

[FLASH]
p10000=IstStart/Пуск по току статора/TWORD/xF000/r2000/A/1/2//1/x0014/
p10100=IstStop/Стоп по току статора/TWORD/xF002/r2001/A/1/2//1/x000A/
p10200=IstExcEnable/Допустимый ток статора перед подачей возбуждения/TWORD/xF004/r2002/A/1/2//1/x0190/
p10300=ExcEnableFreq/Минимальная частота скольжения перед подачей возбуждения/TWORD/xF006/r2003/Hz/0.1/2//1/x0019/
p10400=HsFreq/(Тяжёлый пуск)Максимальная частота скольжения перед подачей возбуждения/TWORD/xF008/r2004/Hz/0.1/2//1/x0032/

[EVENTS]
;авариии
0=FAULT/a/0/Аварий//
;информация
1=PWR/i/0/Выпрямитель включен/На тиристоры выпрямителя поданы импульсы управления/
2=Test/i/0/Режим опробования/Возбудитель включен в режим опробования (проверка цепи скольжения и уставки рабочего тока в ручном режиме)/
3=iMMSState/i/0/Выключатель включен/БК выключателя в состоянии "Включен"/
4=StartProcEnable/i/0/Двигатель включен//
5=oREADY_K2/i/0/Готовность к работе/Готовность к работе 1-разрешена, 0-запрещена/


[STAT]
CNT0=0:0,0:1/2/0/Время работы контроллера (в секундах)/
CNT1=4:1/2/0/Время работы двигателя(в секундах)/

[vars]
AINK=0,00388
CINScale=0,0226
